### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by tbeck** [interledger/interledger-website#1]
**Request:**
Is it possible to add an FAQ section at the top of the site, like they have on the Grant for the Web site: https://www.grantfortheweb.org/? Ideally, we’d love to have each question be a drop down set up, again like they have on the Grant for the Web site. Is this doable? If the section is added, I assume we would be able to add the questions ourselves, but let us know if you’d like us to send you the copy (we’re working on getting final approval).

**Relevant Links:**
https://www.grantfortheweb.org/faq

**Design direction:**
Try to utilize existing design styles. Answers should be collapsible.

**Comment by tbeck** [comment]
@mccamon / @bmarbury

This is ready for review and content entry: 
https://valid-sandpaper.cloudvent.net/faq/

CMS:
https://app.cloudcannon.com/32080/editor#sites/88096/explore/pages/faq:/update/faq/

p.s. Hope you enjoy our placeholder humor. :)

**Comment by mccamon** [comment]
Content has been populated.
