### ISSUE TITLE
Xpring

### ISSUE THREAD

**Issue by bmarbury** [interledger/interledger-website#10]
On Take Action page Xpring is referenced.  The have been renamed to RippleX https://ripplex.io/

**Comment by nathanielfostanperry** [comment]
@bmarbury I swapped out the references to xpring but this is content that should probably be edited by a content manger through the CMS to double check the info. [Link](https://frank-beach.cloudvent.net/take-action/#content-creators)

**Comment by bmarbury** [comment]
Thanks!
