### ISSUE TITLE
Our Work>Impact

### ISSUE THREAD

**Issue by bmarbury** [interledger/interledger-website#12]
Please move the $8M down to align with the rest of the text; it's too high.  Also, please enlarge the icons.

**Comment by mccamon** [comment]
Looks like that content block is different than the other two on that page. When fixing it would be good for the whole block to be editable in the CMS.

**Comment by nathanielfostanperry** [comment]
@bmarbury  This page has been updated [here](https://frank-beach.cloudvent.net/our-work/)

@mccamon fixed the issue with the one column in CMS so the whole block is editable now

**Comment by bmarbury** [comment]
Great!
