### ISSUE TITLE
Generic Signup Form in Footer

### ISSUE THREAD

**Issue by mccamon** [interledger/interledger-website#13]
Here is the link - it is an iframe. 

<iframe src="https://app.e2ma.net/app2/audience/signup/1940649/1929074/" width="510" height="500" frameborder="0"></iframe>

**Comment by mccamon** [comment]
Feature request is a "Join Mailing List" button to left of social roll in footer with treatment similar to JOIN (in main nav). @tbeck

**Comment by nathanielfostanperry** [comment]
@mccamon This issue is live on [staging](https://frank-beach.cloudvent.net/). 

Would recommend whomever is maintaining this embed remove the Interledger ID from the top of the form

**Comment by mccamon** [comment]
Thx. Scroll bar is weird but good enough for launch

**Comment by nathanielfostanperry** [comment]
@mccamon I just updated the height of the iframe so it shouldn't scroll any longer..

With how long the form is though I'm expecting users to have to scroll within the modal as it's ~1200px long
