### ISSUE TITLE
Add "Board of Directors" section

### ISSUE THREAD

**Issue by tbeck** [interledger/interledger-website#2]
**Request:**
Add a Board of directors list under the “Our People” section. This is going to be just a list, like the below, no headshots or full bios. We were envisioning this falling after the Our People section and before Our Funders, but we’re open to your thoughts on what might look best.

### BOARD OF DIRECTORS:

- Stefan Thomas, Chairperson of the Interledger Foundation, Founder and CEO of Coil, and Co-Founder of the Interledger Protocol
- Chris Larsen, Chairperson of Ripple
- Konstantin Peric, Deputy Director of Financial Services for the Poor, Bill and Melinda Gates Foundation
- Maha Bahou, CEO of Jordan Payments and Clearing Company (JoPACC)
- Evan Schwartz, President of the Interledger Foundation, and Co-Founder of the Interledger Protocol
- Briana Marbury, Executive Director of the Interledger Foundation

### OFFICERS:

- Chairperson: Stefan Thomas, Founder and CEO of Coil, and Co-Founder of the Interledger Protocol
- President: Evan Schwartz, Co-Founder of the Interledger Protocol
- Executive Director: Briana Marbury
- Treasurer: Gary Morris, COO of Coil

**Relevant Links:**
https://interledger.name/about-us/

**Design direction:**
Try to utilize existing design styles.

**Comment by tbeck** [comment]
@mccamon / @bmarbury 
This is available for review on the staging site: https://valid-sandpaper.cloudvent.net/about-us/

We can create a PR/Merge back into the production (main) branch when it is ready to push live.

**Comment by nathanielfostanperry** [comment]
@mccamon

Added one for each section of people here
about-us/#our-people

**Comment by mccamon** [comment]
verified. Thx!

**Comment by bmarbury** [comment]
@tbeck @nathanielfostanperry I think the way you have it above looks best.  The way it is in the staging link is too busy.  If you need to keep it that way, I would take everyone's title's out and just put Board Member with the exception of Stefan, Evan, Gary, and myself since we hold other roles in addition to being Board members.  But the way it's listed above is preferable.

**Comment by bmarbury** [comment]
Great!  Looks good.
