### ISSUE TITLE
Refactor News Page and add Coverage Listview Page

### ISSUE THREAD

**Issue by mccamon** [interledger/interledger-website#22]
@tbeck I'm not an expert but below I thought the through the logic but I don't have the core style tools to get this closer to finish line nor am I completely certain how Cloudcannon populated editable collections that end up in front matter. Page title is "Recent Coverage"

Here's the first shot...

```

---
layout: default
title: "Interledger Recent Coverage"
coverage:
  - publication: Forbes
    title: Interledger Foundation Aims To Make Web Payments As Easy As Email
    url: https://www.forbes.com/sites/tomgroenfeldt/2021/04/20/interledger-foundation-aims-to-make-web-payments-as-easy-as-email/?sh=2710c96f7249
    date: 2021-04-20
  - publication: The Paypers
    title: Interledger Foundation launches as a charitable nonprofit organisation
    url: https://thepaypers.com/payments-general/interledger-foundation-launches-as-a-charitable-nonprofit-organisation--1248395
    date: 2021-04-15
---

<section>
  <h1 class="text-uppercase text-purple ">Recent Coverage</h1>
  <ul>
  {% assign sorted-coverage = site.coverage | sort: 'date' | reverse %}
    {% for article in sorted-coverage %}
         <li> {{ article.date }}, {{ article.publication }} - <a href="{{ article.url }}">{{ article.title }}</a></li>
    {% endfor %}
</section>

```

**Comment by nathanielfostanperry** [comment]
@mccamon Do we want to include this in main navigation? We can also explore building out a simple footer nav or open to other ideas? My main concern here is adding too many items there will force us to use a hamburger menu at even desktop sizes.

**Comment by mccamon** [comment]
How about we just have a text link at the top of the news page for now? Recent Coverage.  I might start thinking about an updated layout to the News page in general. Maybe we go with three groupings of content: (1) Featured, (2) Recent Coverage, (3) News and Blog.  The first two could be list format - and the featured group could be news/blog posts that have a "featured" tag.  Thoughts?

**Comment by nathanielfostanperry** [comment]
@mccamon Sounds good to me! Would you mind opening a separate issue for combining those? 

This issue is up on [staging here ](https://frank-beach.cloudvent.net/news/press/) for review.

**Comment by mccamon** [comment]
Also wondering if we should change the header link from NEWS to NEWS & BLOG

**Comment by mccamon** [comment]
Draft mockup https://wireframepro.mockflow.com/view/ 
Me74c2012a66b812beae644b7b043f41c1622058950066

**Comment by mccamon** [comment]
Added Listview page for when there are more coverage stories. These stories are not stored on the site, only links to the source article.

**Comment by nathanielfostanperry** [comment]
@mccamon We've refactored the [news page here](https://frank-beach.cloudvent.net/news/) for review. 

• Up top we have up to 5 featured news items (the first one kind of acting like a hero item). Below that, added another CTA to sign up for the mailing list that is also present in the footer. 

• Recent coverage below that, currently limited to 4 items but with a link to a separate page to view all.

• Latest updates from Interledger below that, same deal but should be limited to 8 items.

These items are all entered as news items in a collection so both Recent Coverage and Interledger Updates can be created the same way in Cloudcannon with a dropdown selecting either or. Also updated card styles a bit to make them feel more cohesive together with the long titles.

**Comment by mccamon** [comment]
Getting feedback from team

**Comment by mccamon** [comment]
> @mccamon Do we want to include this in main navigation? We can also explore building out a simple footer nav or open to other ideas? My main concern here is adding too many items there will force us to use a hamburger menu at even desktop sizes (>1200px).

I think we just leave the menu "NEWS" and this is the REFACTORED News page instead of another one for the nav.  Most traffic these days is search driven to internal landing pages IMHO

**Comment by mccamon** [comment]
It would be helpful to keep publication as a unique field for this data collection as opposed to overloading the title. See initial proposed front matter above

**Comment by mccamon** [comment]
Close. What @tbeck and I discussed earlier today was.... FEATURED will only be ONE article in the "wide screen" format. Recent Coverage is correct. Latest Updates would retain the bigger tile design that is currently in production.

**Comment by nathanielfostanperry** [comment]
@mccamon [this is ready for review](https://frank-beach.cloudvent.net/news). 

- Updated 'news' to 'stories' in the CMS (small quirk with how cloudcannon handles pluralized collections, 'news' in this case doesn't work too well with a single featured banner). 
- A single story can be set as the[ banner item](https://gyazo.com/9ff1196a708c6dda0481728cf0fbd907) (widescreen) and other featured items will appear as cards below that. 
- Also added a publication field that will show up next to the date if entered
- Removed display images on cards to help with scalability (the featured banner item still has an image)
- Adjusted button to be same styles for both offsite and onsite articles
