### ISSUE TITLE
Monetize the Interledger foundation website

### ISSUE THREAD

**Issue by uchibeke** [interledger/interledger-website#28]
Add the Interledger Foundation's Payment Pointer to the head of the Foundation's website.

https://developers.coil.com/

`<meta name="monetization" content="$your.payment.pointer.address/xxx">`

**Comment by nathanielfostanperry** [comment]
@mccamon can you provide the Interledger wallet address

**Comment by mccamon** [comment]
Working to get wallet id.

**Comment by nathanielfostanperry** [comment]
@mccamon This has been added to the HEAD. Can you confirm on your end
