### ISSUE TITLE
Calls page returns 404

### ISSUE THREAD

**Issue by ioana-chiorean** [interledger/interledger-website#48]
1. Go to interledger website - Communtiy tab https://interledger.org/developer-tools/community/
2. Go to section: Bi-Weekly Calls
3. Check last https://interledger.org/calls.html 

Expected:
- you should be able to see details about the calls

Actual: 
- you get 404

<img width="1199" alt="Screenshot 2021-09-27 at 18 44 22" src="https://user-images.githubusercontent.com/1391451/134941285-33412e79-aefd-4939-bdfe-1e0b0e44037e.png">

**Comment by devcer** [comment]
I think this issue is invalid now since there is no `Bi-weekly Calls` section. All the links on `Monthly Calls` section seem to work fine.

**Comment by AlexLakatos** [comment]
I think you're right. Nice spot.
