### ISSUE TITLE
Blog posts do not sort in desc date order

### ISSUE THREAD

**Issue by mccamon** [interledger/interledger-website#5]
Created three blog posts and regardless of the date field the sort on the page was in their original order (ID?)

**Comment by mccamon** [comment]
Have verified that blog posts with publication date in future do not appear on the NEWS page.

**Comment by tbeck** [comment]
@mccamon 
We will update to force desc order on posts. Assigning to @nathanielfostanperry to complete and post staging url when it is ready for review.

Just to confirm... Is the future post behavior what you expected?

**Comment by mccamon** [comment]
Thx. Yes I did test that “future” posts do not appear until their publication date. I didn’t stress test this, but informally it looks to behave correctly. 

================
Mike McCamon
913.940.2737
"Always do right. This will gratify some people, and astonish the rest." - Mark Twain

**Comment by nathanielfostanperry** [comment]
@mccamon 

Have a few test posts [staged here](https://frank-beach.cloudvent.net/news/) descending by the set date rather than post order.  There's a 4th post with a future date we aren't seeing to confirm future dated posts are still not showing.

**Comment by mccamon** [comment]
verified. Also added one same day with different time and sorting worked properly
