### ISSUE TITLE
Increase Logo

### ISSUE THREAD

**Issue by bmarbury** [interledger/interledger-website#7]
Is there a way to increase the logo on the banner?

**Comment by tbeck** [comment]
Hi @bmarbury 
Yes... we can bump up the size a bit. Do you have any specific sizing in mind or should we use our best judgement?

@nathanielfostanperry - Please post a staging url here for review.

Thanks!

**Comment by nathanielfostanperry** [comment]
@bmarbury 

I bumped this up a bit, how is [this sizing](https://gyazo.com/14e97df13b94584ac1b4769e4a9d1dba) looking with the rest of the nav?
[Staging link](https://frank-beach.cloudvent.net/)

**Comment by bmarbury** [comment]
Looks good!
